name: Label New Issue or PR

on:
  issues:
    types: [opened]
  discussion:
    types: [created]
  pull_request:
    types: [opened]

jobs:
  assign-label:
    runs-on: ubuntu-latest

    steps:
      - name: Check user permissions and assign label
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            let label = '';

            const isPullRequest = github.event_name === 'pull_request';
            const username = isPullRequest ? github.event.pull_request.user.login : github.event.issue.user.login;

            const collaboratorResponse = await github.repos.checkCollaborator({
              owner: context.repo.owner,
              repo: context.repo.repo,
              username: username
            });

            if (collaboratorResponse.status === 204) {
              console.log('Contributor');
              label = 'Prio Urgent';
            } else {
              const adafruitResponse = await github.orgs.checkMembership({
                org: 'adafruit',
                username: username
              });

              if (adafruitResponse.status === 204) {
                console.log('Adafruit Member');
                label = 'Prio Urgent';
              } else {
                console.log('Not a contributor or Adafruit member');
              }
            }

            if (label !== '') {
              await github.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue?.number || context.payload.pull_request?.number,
                labels: [label]
              });
            }
