name: Label New Issue

on:
  issues:
    types: [opened]

jobs:
  assign-label:
    runs-on: ubuntu-latest

    steps:
      - name: Label New Issue
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            let label = '';

            const collaboratorResponse = await github.rest.repos.checkCollaborator({
              owner: context.repo.owner,
              repo: context.repo.repo,
              username: context.payload.issue.user.login
            });

            if (collaboratorResponse.status === 204) {
              console.log('Contributor');
              label = 'Prio Urgent';
            } else {
              const adafruitResponse = await github.rest.orgs.checkMembership({
                org: 'adafruit',
                username: context.payload.issue.user.login
              });

              if (adafruitResponse.status === 204) {
                console.log('Adafruit Member');
                label = 'Prio Urgent';
              } else {
                console.log('Not a contributor or Adafruit member');
              }
            }

            if (label !== '') {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.issue.number,
                labels: [label]
              });
            }
