name: Label New Issue, PR, or Discussion

on:
  issues:
    types: [opened]
  discussion:
    types: [created]
  pull_request:
    types: [opened]

jobs:
  assign-label:
    runs-on: ubuntu-latest

    steps:
      - name: Check user permissions and assign label
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log(JSON.stringify(github.event));

            let label = '';
            let issueNumber;
            let username;

            if (github.event_name === 'pull_request') {
              username = github.event.pull_request.user.login;
              issueNumber = github.event.pull_request.number;
            } else if (github.event_name === 'discussion') {
              username = github.event.sender.login;
              issueNumber = context.issue.number;
            } else {
              username = github.event.issue.user.login;
              issueNumber = context.issue.number;
            }

            console.log('Username:', username);
            console.log('Issue number:', issueNumber);

            const collaboratorResponse = await github.repos.checkCollaborator({
              owner: context.repo.owner,
              repo: context.repo.repo,
              username: username
            });

            if (collaboratorResponse.status === 204) {
              console.log('Contributor');
              label = 'Prio Urgent';
            } else {
              const adafruitResponse = await github.orgs.checkMembership({
                org: 'adafruit',
                username: username
              });

              if (adafruitResponse.status === 204) {
                console.log('Adafruit Member');
                label = 'Prio Urgent';
              } else {
                console.log('Not a contributor or Adafruit member');
              }
            }

            if (label !== '') {
              await github.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                labels: [label]
              });
            }
